version: "3.8"

services:
  fragments:
    init: true
    build: .
    environment:
      - PORT=8080
      - API_URL=http://localhost:8080
      - AUTH_STRATEGY=basic
      - HTPASSWD_FILE=tests/.htpasswd
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
    ports:
      - "8080:8080"
    depends_on:
      - localstack
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local
    
    ports:
      - "8000:8000"

  # Run the database in memory, see:
    # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']

  localstack:
    # https://hub.docker.com/r/localstack/localstack
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      # See https://docs.localstack.cloud/localstack/configuration/ and
      # https://hub.docker.com/r/localstack/localstack for config details.
      # We only want to run S3
      - SERVICES=s3
      # We're always working in us-east-1
      - DEFAULT_REGION=us-east-1
